version: '3'

services:
  zaproxy:
    image: owasp/zap2docker-weekly
    command: sleep 3600
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - OIDC_RP_CLIENT_ID=${OIDC_RP_CLIENT_ID}
      - OIDC_OP_AUTHORIZATION_ENDPOINT=${OIDC_OP_AUTHORIZATION_ENDPOINT}
      - OIDC_OP_TOKEN_ENDPOINT=${OIDC_OP_TOKEN_ENDPOINT}
      - OIDC_OP_USER_ENDPOINT=${OIDC_OP_USER_ENDPOINT}
      - OIDC_OP_JWKS_ENDPOINT=${OIDC_OP_JWKS_ENDPOINT}
      - ACR_VALUES=${ACR_VALUES}

    image: tdp
    build:
     context: .
     dockerfile: ./docker/local/Dockerfile
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/tdpapp
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/tdpapp
    ports:
      - "8001:8001"
