# Base Docker compose for all environments
version: "3.4"

services:
  web:
    restart: always
    env_file:
      - .env.ci
    volumes:
      - .:/tdpapp
    image: tdp
    build: .
    command: bash -c "gunicorn -c gunicorn_prod_cfg.py"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5555:5555"