# Base Docker compose for all environments
version: "3"

services:
  zaproxy:
    image: owasp/zap2docker-weekly
    command: sleep 3600
  postgres:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=tdpuser
      - POSTGRES_PASSWORD=something_secure
      - POSTGRES_DB=tdrs_test
      - POSTGRES_PORT=5432
  localstack:
    image: localstack/localstack:0.12.9
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/tmp/localstack
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DB_USER=tdpuser
      - DB_PASSWORD=something_secure
      - DB_NAME=tdrs_test
      - DB_PORT=5432
      - DB_HOST=postgres
      - DJANGO_SETTINGS_MODULE=tdpservice.settings.local
      - DJANGO_CONFIGURATION=Local
      - USE_LOCALSTACK=1
      - JWT_KEY=${JWT_KEY}
      - JWT_CERT_TEST=${JWT_CERT_TEST}
      - DJANGO_SU_NAME=${DJANGO_SU_NAME}
    volumes:
      - .:/tdpapp
    image: tdp
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    command: >
      bash -c "python wait_for_postgres.py &&
               ./gunicorn_start.sh"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - localstack
volumes:
  localstack_data:
