CREATE ROLE readaccess;
GRANT CONNECT ON DATABASE $DB_NAME TO readaccess;
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;
CREATE USER $GRAFANA_USER WITH PASSWORD '$GRAFANA_PASSWORD';
GRANT readaccess TO $GRAFANA_USER;

CREATE ROLE OFA_ADMIN;
GRANT CONNECT ON DATABASE $DB_NAME TO OFA_ADMIN;
GRANT USAGE ON SCHEMA public TO OFA_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO OFA_ADMIN;
REVOKE ALL ON (SELECT * FROM information_schema."tables" t  WHERE TABLE_NAME LIKE 'django%') FROM OFA_ADMIN;
CREATE USER $OFA_USER WITH PASSWORD '$OFA_PASSWORD';
GRANT OFA_ADMIN TO $OFA_USER;

CREATE ROLE OFA_DB_ADMIN;
GRANT CONNECT ON DATABASE $DB_NAME TO OFA_DB_ADMIN;
GRANT USAGE ON SCHEMA public TO OFA_DB_ADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA public TO OFA_DB_ADMIN;
GRANT pg_read_all_data TO OFA_DB_ADMIN;
GRANT pg_write_all_data TO OFA_DB_ADMIN;
CREATE USER $OFA_DB_USER WITH PASSWORD '$OFA_DB_PASSWORD';
GRANT OFA_DB_ADMIN TO $OFA_DB_USER;
