# Generated by Django 3.2.15 on 2022-11-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0011_alter_datafile_section'),
        ('search_indexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_files.datafile')),
            ],
        ),
    ]
