# Generated by Django 3.2.15 on 2022-12-01 17:02

from django.db import migrations, models
import tdpservice.search_indexes.parsers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0002_parserlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1',
            name='fips_code',
        ),
        migrations.AlterField(
            model_name='t1',
            name='record',
            field=models.CharField(max_length=156, validators=[tdpservice.search_indexes.parsers.validators.record]),
        ),
    ]
