# Generated by Django 3.2.15 on 2023-04-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0008_auto_20230424_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanf_t2',
            old_name='education_level',
            new_name='EDUCATION_LEVEL',
        ),
        migrations.RenameField(
            model_name='tanf_t2',
            old_name='employment_status',
            new_name='EMPLOYMENT_STATUS',
        ),
        migrations.RenameField(
            model_name='tanf_t2',
            old_name='family_affiliation',
            new_name='FAMILY_AFFILIATION',
        ),
        migrations.RenameField(
            model_name='tanf_t2',
            old_name='gender',
            new_name='GENDER',
        ),
    ]
