# Generated by Django 3.2.15 on 2023-05-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0008_auto_20230503_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanf_t2',
            name='AMOUNT_OF_EARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CASE_NUMBER',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CHILD_CARE_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CHILD_CARE_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CHILD_CARE_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CITIZENSHIP_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMMUNITY_SVS_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMMUNITY_SVS_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMMUNITY_SVS_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COOPERATION_WITH_CHILD_SUPPORT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CURRENT_MONTH_EXEMPT_FROM_STATE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DOB',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EDUCATION_RELATED_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EDUCATION_RELATED_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EDUCATION_RELATED_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EMPLOYMENT_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='FAMILY_AFFILIATION',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='GENDER',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='MARITAL_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NEEDS_OF_A_PREGNANT_WOMAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NONCUSTODIAL_PARENT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NUMBER_OF_COUNTABLE_MONTHS',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NUMBER_OF_COUNTABLE_MONTHS_REMAINING',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NUMBER_OF_DEEMED_CORE_HOURS_FOR_OVERALL_RATE',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NUMBER_OF_DEEMED_CORE_HOURS_FOR_TWO_PARENT_RATE',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='ON_THE_JOB_TRAINING',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='OTHER_WORK_ACTIVITIES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PARENT_WITH_MINOR_CHILD',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_AMERICAN_INDIAN_OR_ALASKA_NATIVE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_ASIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_BLACK_OR_AFRICAN_AMERICAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_HISPANIC_OR_LATINO',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_WHITE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RECEIVES_AID_TOTALLY_DISABLED_UNDER_TITLE_XIV_APDT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RECEIVES_AID_TO_THE_AGED',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RECEIVES_BENEFITS_BASED_ON_FEDERAL_DISABILITY_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RECEIVES_FEDERAL_DISABILITY_INSURANCE_OASDI_PROGRAM',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RECEIVES_SUPPLEMENTAL_SECURITY_INCOME_TITLE_XVI_SSI',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RELATIONSHIP_TO_HEAD_OF_HOUSEHOLD',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RecordType',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SSN',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SUBSIDIZED_PRIVATE_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SUBSIDIZED_PUBLIC_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_INCOME_EARNED_INCOME_TAX_CREDIT',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_INCOME_OTHER_UNEARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_INCOME_SOCIAL_SECURITY',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_INCOME_SSI',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_INCOME_WORKERS_COMPENSATION',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNSUBSIDIZED_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_ELIGIBLE_INDIVIDUAL_INDICATOR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXP_EXCUSED_ABSENCES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXP_HOLIDAYS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXP_HOURS_OF_PARTICIPATION',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_PARTICIPATION_STATUS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='CASE_NUMBER',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='CITIZENSHIP_ALIENAGE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='DOB',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='FAMILY_AFFILIATION',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='GENDER',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='PARENT_WITH_MINOR_CHILD',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_AMERICAN_INDIAN_OR_ALASKA_NATIVE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_ASIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_BLACK_OR_AFRICAN_AMERICAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_HISPANIC_OR_LATINO',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_WHITE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RECEIVES_BENEFITS_UNDER_NON_SSA_PROGRAMS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RECEIVES_SSI_UNDER_TITLE_XVI_SSI',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RELATIONSHIP_TO_HEAD_OF_HOUSEHOLD',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RecordType',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='SSN',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='UNEARNED_INCOME_OTHER_UNEARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='UNEARNED_INCOME_SSI',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
