# Generated by Django 3.2.15 on 2023-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0008_auto_20230503_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanf_t2',
            name='AID_AGED_BLIND',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CASE_NUMBER',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CITIZENSHIP_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMM_SERVICES_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMM_SERVICES_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMM_SERVICES_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COOPERATION_CHILD_SUPPORT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CURRENT_MONTH_STATE_EXEMPT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DATE_OF_BIRTH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DEEMED_HOURS_FOR_OVERALL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DEEMED_HOURS_FOR_TWO_PARENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DISABLED_TITLE_XIVAPDT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='ED_NO_HIGH_SCHOOL_DIPL_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='ED_NO_HIGH_SCHOOL_DIPL_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='ED_NO_HIGH_SCHOOL_DIPL_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EMPLOYMENT_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='FAMILY_AFFILIATION',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='FED_DISABILITY_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='FED_OASDI_PROGRAM',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='GENDER',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_TRAINING_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_TRAINING_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_TRAINING_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='MARITAL_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='MONTHS_FED_TIME_LIMIT',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='MONTHS_STATE_TIME_LIMIT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NEEDS_PREGNANT_WOMAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NONCUSTODIAL_PARENT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='OJT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='OTHER_UNEARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='OTHER_WORK_ACTIVITIES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PARENT_WITH_MINOR_CHILD',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PROVIDE_CC_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PROVIDE_CC_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PROVIDE_CC_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_AMER_INDIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_ASIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_BLACK',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_HAWAIIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_HISPANIC',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_WHITE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RECEIVE_SSI',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RELATIONSHIP_HOH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RecordType',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SSN',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SUB_PRIVATE_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SUB_PUBLIC_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_INCOME_TAX_CREDIT',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_SOCIAL_SECURITY',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_SSI',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_WORKERS_COMP',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNSUB_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_TRAINING_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_TRAINING_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_TRAINING_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_ELIGIBLE_INDICATOR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXPERIENCE_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXPERIENCE_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXPERIENCE_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_PART_STATUS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='CASE_NUMBER',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='CITIZENSHIP_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='DATE_OF_BIRTH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='FAMILY_AFFILIATION',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='GENDER',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='OTHER_UNEARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='PARENT_MINOR_CHILD',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_AMER_INDIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_ASIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_BLACK',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_HAWAIIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_HISPANIC',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_WHITE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RECEIVE_NONSSA_BENEFITS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RECEIVE_SSI',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RELATIONSHIP_HOH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RecordType',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='SSN',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='UNEARNED_SSI',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
