# Generated by Django 3.2.15 on 2023-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0009_auto_20230424_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanf_t3',
            name='SSN',
            field=models.CharField(max_length=9),
        ),
    ]
