# Generated by Django 3.2.15 on 2023-04-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0010_alter_tanf_t3_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanf_t3',
            name='FAMILY_AFFILIATION',
            field=models.IntegerField(),
        ),
    ]
