version: '3'

tasks:

  init-backend:
    desc: Initialize the backend project
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml up -d --build
      - docker-compose -f docker-compose.yml exec web sh -c "python ./manage.py makemigrations"
      - docker-compose -f docker-compose.yml exec web sh -c "python ./manage.py migrate"
      - docker-compose -f docker-compose.yml down

  drop-db:
    desc: Drop the backend database
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml down
      - docker volume rm tdrs-backend_postgres_data

  backend-up:
    desc: Start backend web server
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml up -d

  backend-down:
    desc: Stop backend web server
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml down

  backend-logs:
    desc: Show and follow backend web server logs
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml logs -f

  backend-restart:
    desc: Restart backend web server
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml restart -d

  backend-bash:
    desc: Open a shell in the backend container
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml exec web sh

  backend-shell:
    desc: Open a Django shell in the backend container
    dir: tdrs-backend
    cmds:
      - docker-compose -f docker-compose.yml exec web sh -c "python ./manage.py shell"

  test:
    desc: Execute tests
    env:
      PYTEST_ARGS: '{{.PYTEST_ARGS | default "."}}'
    cmds:
      - docker-compose up test-app -d
      - docker-compose exec test-app sh -c "pytest $PYTEST_ARGS"
      - task test-e2e

  backend-pytest:
    desc: 'Run pytest in the backend container E.g: task backend-pytest PYTEST_ARGS="tdpservice/test/ -s -vv"'
    dir: tdrs-backend
    vars:
      PYTEST_ARGS: '{{.PYTEST_ARGS | default "."}}'
    cmds:
      - task backend-up
      - docker-compose -f docker-compose.yml exec web sh -c "pytest {{.PYTEST_ARGS}}"

  frontend-up:
    desc: Start frontend web server
    dir: tdrs-frontend
    cmds:
      - docker-compose -f docker-compose.yml up -d

  frontend-bash:
    desc: Open a shell in the frontend container
    dir: tdrs-frontend
    cmds:
      - docker-compose -f docker-compose.yml exec tdp-frontend sh

  up:
    desc: Start both frontend and backend web servers
    cmds:
      - task: backend-up
      - task: frontend-up

  down:
    desc: Stop both frontend and backend web servers
    cmds:
      - task: backend-down
      - task: frontend-down

  help:
    desc: Show this help message
    cmds:
      - task --list