# commands:
  init-deploy:
    steps:
      - checkout
      - sudo-check
      - cf-check

  build-and-tag-images:
    parameters:
      backend-appname:
        default: tdp-backend
        type: string
      frontend-appname:
        default: tdp-frontend
        type: string
    steps:
      - run:
          name: Update Docker daemon
          command: |
            sudo echo '{"max-concurrent-uploads": 1}' | sudo tee /etc/docker/daemon.json
            sudo service docker restart
      - run:
          name: Create builder
          command: |
            docker buildx create --name container-builder --driver docker-container --use --bootstrap
      - run:
          name: Build and tag images
          command: |
            ./scripts/build-and-tag-images.sh <<parameters.backend-appname>> <<parameters.frontend-appname>> ./tdrs-backend ./tdrs-frontend $CIRCLE_BUILD_NUM $CIRCLE_SHA1 "$CIRCI_DOCKER_LOGIN" tdp-circi

  deploy-cloud-dot-gov:
    parameters:
      environment:
        description: The environment to deploy to.
        type: enum
        enum: [ "development", "production" ]
        default: development
      backend-appname:
        default: tdp-backend
        type: string
      cf-password:
        default: CF_PASSWORD_DEV
        type: env_var_name
      cf-org:
        default: CF_ORG
        type: env_var_name
      cf-space:
        default: tanf-dev
        type: string
      cf-username:
        default: CF_USERNAME_DEV
        type: env_var_name
      frontend-appname:
        default: tdp-frontend
        type: string
    steps:
      - login-cloud-dot-gov:
          cf-password: <<parameters.cf-password>>
          cf-org: <<parameters.cf-org>>
          cf-space: <<parameters.cf-space>>
          cf-username: <<parameters.cf-username>>
      - deploy-backend:
          backend-appname: <<parameters.backend-appname>>
          frontend-appname: <<parameters.frontend-appname>>
          cf-space: <<parameters.cf-space>>
      - deploy-frontend:
          environment: <<parameters.environment>>
          backend-appname: <<parameters.backend-appname>>
          frontend-appname: <<parameters.frontend-appname>>
          cf-space: <<parameters.cf-space>>

  clamav-cloud-dot-gov:
    parameters:
      backend-appname:
        default: tdp-backend
        type: string
      cf-password:
        default: CF_PASSWORD_DEV
        type: env_var_name
      cf-org:
        default: CF_ORG
        type: env_var_name
      cf-space:
        default: tanf-dev
        type: string
      cf-username:
        default: CF_USERNAME_DEV
        type: env_var_name
    steps:
      - checkout
      - sudo-check
      - cf-check
      - login-cloud-dot-gov:
          cf-password: <<parameters.cf-password>>
          cf-org: <<parameters.cf-org>>
          cf-space: <<parameters.cf-space>>
          cf-username: <<parameters.cf-username>>
      - deploy-clamav

  deploy-backend:
    parameters:
      backend-appname:
        default: tdp-backend
        type: string
      frontend-appname:
        default: tdp-frontend
        type: string
      kibana-appname:
        default: tdp-kibana
        type: string
      proxy-appname:
        default: tdp-elastic-proxy
        type: string
      cf-space:
        default: tanf-dev
        type: string
    steps:
      - get-app-deploy-strategy:
          appname: <<parameters.backend-appname>>
      - run:
          name: Apply database migrations
          command: |
            bash ./scripts/apply-remote-migrations.sh <<parameters.backend-appname>>
      - run:
          name: Prepare backend application
          command: |
            bash ./scripts/prepare-backend.sh \
              $DEPLOY_STRATEGY \
              <<parameters.frontend-appname>> \
              <<parameters.backend-appname>> \
              <<parameters.kibana-appname>> \
              <<parameters.proxy-appname>> \
              <<parameters.cf-space>>

  deploy-clamav:
    steps:
      - run:
          name: Deploy ClamAV REST application
          command: |
            cf push clamav-rest -f tdrs-backend/manifest.clamav.yml \
              --var cf-space=tanf-prod

  deploy-frontend:
    parameters:
      environment:
        description: The environment to deploy to.
        type: enum
        enum: [ "development", "production" ]
        default: development
      backend-appname:
        default: tdp-backend
        type: string
      frontend-appname:
        default: tdp-frontend
        type: string
      kibana-appname:
        default: tdp-kibana
        type: string
# So the frontend knows what space its in for the banner.
# I am unclear if the domain is a reliable metric to make this function
# It seems like it might not be working
      cf-space:
        default: dev
        type: string
    steps:
      - install-nodejs:
          node-version: "16.13"
      - disable-npm-audit
      - install-nodejs-packages:
          app-dir: tdrs-frontend
      - get-app-deploy-strategy:
          appname: <<parameters.frontend-appname>>
      - run:
          name: Prepare frontend application
          command: |
            bash ./scripts/deploy-frontend.sh \
              $DEPLOY_STRATEGY \
              <<parameters.frontend-appname>> \
              <<parameters.backend-appname>> \
              <<parameters.kibana-appname>> \
              <<parameters.cf-space>> \
              <<parameters.environment>>

  get-app-deploy-strategy:
    parameters:
      appname:
        type: string
    steps:
      - run:
          name: Determine deploy strategy
          command: |
            # NOTE: The || true is a no-op included to suppress exit codes which
            #       would cause the step to exit early due to use of pipefail
            APP_GUID=$(cf app <<parameters.appname>> --guid || true)
            if [ "$APP_GUID" == "FAILED" ]; then
              echo "export DEPLOY_STRATEGY=initial" >> $BASH_ENV
            else
              echo "export DEPLOY_STRATEGY=rolling" >> $BASH_ENV
            fi

  deploy-infrastructure:
    parameters:
      tf-path:
        type: string
        default: ./terraform/dev
      cf-password:
        type: env_var_name
        default: CF_PASSWORD_DEV
      cf-username:
        type: env_var_name
        default: CF_USERNAME_DEV
      cf-space:
        type: string
        default: tanf-dev
      cf-org:
        type: env_var_name
        default: CF_ORG
      cf-app:
        type: string
        default: CF_APP
    steps:
      - checkout
      - sudo-check
      - cf-check
      - login-cloud-dot-gov:
          cf-password: <<parameters.cf-password>>
          cf-username: <<parameters.cf-username>>
          cf-space: <<parameters.cf-space>>
      - run:
          name: Terraform Install Check
          command: |
            bash ./scripts/terraform-check.sh
      - run:
          name: Create Env Vars & Credentials for TFState
          command: |
            strip() {
                # Usage: strip "string" "pattern"
                printf '%s\n' "${1##$2}"
            }
            # The cloud.gov space defined via environment variable (e.g., "tanf-dev", "tanf-staging")
            env=$(strip <<parameters.cf-space>> "tanf-")
            # scripts take these: 'dev', 'staging', 'production'. but 'prod' would be passed in
            if [ $env == "prod" ]; then
              env="production"
            fi
            cd terraform
            bash ./create_backend_vars.sh $env
            bash ./create_tf_vars.sh $env 
            
            #TODO: need to tell terraform which app to update using the cf-app parameter
            echo "export CF_APP=<<parameters.cf-app>>" >> terraform/$env/variables.tfvars

            #debugging, verifying var files get created
            ls -al
      - run:
          name: Terraform Init
          command: |
           strip() {
             # Usage: strip "string" "pattern"
             printf '%s\n' "${1##$2}"
           }
           # The cloud.gov space defined via environment variable (e.g., "tanf-dev", "tanf-staging")
           env=$(strip <<parameters.cf-space>> "tanf-")
           cd ./terraform/$env
           terraform init -backend-config backend_config.tfvars -var-file variables.tfvars
           terraform validate
           terraform plan -out tfapply -var-file ./variables.tfvars
           terraform apply tfapply

  enable-s3-versioning:
    parameters:
      target_env:
        type: string
      cf-password:
        type: env_var_name
      cf-username:
        type: env_var_name
      cf-space:
        type: string
    steps:
      - checkout
      - cf-check
      - login-cloud-dot-gov:
          cf-password: <<parameters.cf-password>>
          cf-username: <<parameters.cf-username>>
          cf-space: <<parameters.cf-space>>
      - run:
          name: Ensure s3 versioning key exists
          # use cf to check if a service key exists for tdp-datafiles-dev(or prod)
          # exit 0 if it does, create it if it doesn't
          command: |
            chmod +x ./scripts/create_s3_versioning_key.sh
            ./scripts/create_s3_versioning_key.sh tdp-datafiles-<<parameters.target_env>> s3-versioning-key
      - run:
          name: Set up aws credentials
          command: |
            S3_CREDENTIALS=$(cf service-key tdp-datafiles-<<parameters.target_env>> s3-versioning-key | tail -n +2)
            aws configure set aws_access_key_id $(echo "${S3_CREDENTIALS}" | jq -r .access_key_id)
            aws configure set aws_secret_access_key $(echo "${S3_CREDENTIALS}" | jq -r .secret_access_key)
            aws configure set default.region $(echo "${S3_CREDENTIALS}" | jq -r '.region')
      - run:
          name: Enable S3 Versioning
          command: |
            S3_BUCKET_ID=cg-$(cf service tdp-datafiles-<<parameters.target_env>> --guid)
            aws s3api put-bucket-versioning --bucket ${S3_BUCKET_ID} --versioning-configuration Status=Enabled
