#workflows:
  deployment:
    when:
      and:
        - or:
            - equal: [ master, << pipeline.git.branch >> ]
            - equal: [ main, << pipeline.git.branch >> ]
            - equal: [ develop, << pipeline.git.branch >> ]
            - << pipeline.parameters.run_dev_deployment >>
        - not: << pipeline.parameters.run_nightly_owasp_scan >>

    jobs:
      - deploy-project-updates-site:
              only: - develop
      - deploy-infrastructure-dev:
              ignore:
                - develop
                - main
                - master
      - deploy-infrastructure-staging:
              only:
                - develop
                - main
      - deploy-infrastructure-production:
              only:  - master

      - prod-deploy-clamav:
          requires:
            - deploy-infrastructure-production
          filters:
            branches:
              only:
                - master
      - deploy-dev:
          target_env: << pipeline.parameters.target_env >>
          requires:
            - deploy-infrastructure-dev
          filters:
            branches:
              ignore:
                - develop
                - main
                - master
      - build-and-tag-develop:
          requires:
            - deploy-infrastructure-staging
          filters:
            branches:
              only:
                - develop
      - deploy-develop:
          requires:
            - build-and-tag-develop
          filters:
            branches:
              only:
                - develop
      - build-and-tag-staging:
          requires:
            - deploy-infrastructure-staging
          filters:
            branches:
              only:
                - main
      - deploy-staging:
          requires:
            - build-and-tag-staging
          filters:
            branches:
              only:
                - main
      - build-and-tag-production:
          requires:
            - deploy-infrastructure-production
          filters:
            branches:
              only:
                - master
      - deploy-production:
          requires:
            - build-and-tag-production
          filters:
            branches:
              only:
                - master
      - test-deployment-e2e:
          requires:
            - deploy-develop
          filters:
            branches:
              only:
                - develop
      - make_erd: # from ../util folder
          filters:
            branches:
              only:
                - develop
                - master
