#workflows:
  dev-deployment:
    when:
      << pipeline.parameters.run_dev_deployment >>
    jobs:
      - deploy-infrastructure-dev:
          target_env: << pipeline.parameters.target_env >>
      - deploy-dev:
          target_env: << pipeline.parameters.target_env >>
          requires:
            - deploy-infrastructure-dev

  staging-deployment:
    unless: 
      or:
        - << pipeline.parameters.run_dev_deployment >>
        - << pipeline.parameters.run_nightly_owasp_scan >>
    jobs:
      - deploy-project-updates-site:
          filters:
            branches:
              only:
                - 1544-Nginx-with-domain # switch back to develop before merge
      - deploy-infrastructure-staging:
          filters:
            branches:
              only:
                - main
      - deploy-staging:
          requires:
            - deploy-infrastructure-staging
          filters:
            branches:
              only:
                - main
      - deploy-infrastructure-develop:
          filters:
            branches:
              only:
                - 1544-Nginx-with-domain # switch back to develop before merge
      - deploy-develop:
          requires:
            - deploy-infrastructure-develop
          filters:
            branches:
              only:
                - 1544-Nginx-with-domain # switch back to develop before merge
      - test-deployment-e2e:
          requires:
            - deploy-develop
          filters:
            branches:
              only:
               - 1544-Nginx-with-domain # switch back to develop before merge

  production-deployment:
    unless:
      or:
        - << pipeline.parameters.run_dev_deployment >>
        - << pipeline.parameters.run_nightly_owasp_scan >>
    jobs:
      - deploy-infrastructure-production:
          filters:
            branches:
              only:
                - master
      - deploy-production:
          requires:
            - deploy-infrastructure-production
          filters:
            branches:
              only:
                - master
