#workflows:
  dev-deployment:
    when:
      << pipeline.parameters.run_dev_deployment >>
    jobs:
      - deploy-infrastructure-dev:
          target_env: << pipeline.parameters.target_env >>
      - deploy-dev:
          target_env: << pipeline.parameters.target_env >>
          requires:
            - deploy-infrastructure-dev

  staging-deployment:
    unless:
      or:
        - << pipeline.parameters.run_dev_deployment >>
        - << pipeline.parameters.run_nightly_owasp_scan >>
    jobs:
      - deploy-project-updates-site:
          filters:
            branches:
              only:
                - develop
      - deploy-infrastructure-staging:
          filters:
            branches:
              only:
                - main
      - deploy-staging:
          requires:
            - deploy-infrastructure-staging
          filters:
            branches:
              only:
                - main
      - deploy-infrastructure-develop:
          filters:
            branches:
              only:
                - develop
      - deploy-develop:
          requires:
            - deploy-infrastructure-develop
          filters:
            branches:
              only:
                - develop
      - test-deployment-e2e:
          requires:
            - deploy-develop
          filters:
            branches:
              only:
                - develop

  production-deployment:
    unless:
      or:
        - << pipeline.parameters.run_dev_deployment >>
        - << pipeline.parameters.run_nightly_owasp_scan >>
    jobs:
      - deploy-infrastructure-production:
          filters:
            branches:
              only:
                - master
      - deploy-production:
          requires:
            - deploy-infrastructure-production
          filters:
            branches:
              only:
                - master

  dev-apps-fs-upgrade:
    when:
      << pipeline.parameters.upgrade_dev_apps_fs >>
    jobs:
      - upgrade-cf-dev-apps:
          filters:
            branches:
              only:
                - develop

  staging-apps-fs-upgrade:
    when:
      << pipeline.parameters.upgrade_staging_apps_fs >>
    jobs:
      - upgrade-cf-staging-apps:
          filters:
            branches:
              only:
                - develop

  prod-apps-fs-upgrade:
    unless:
      when:

        << pipeline.parameters.upgrade_prod_apps_fs >>
    jobs:
      - upgrade-cf-prod-apps:
          filters:
            branches:
              only:
                - master
