# Generated by Django 3.2.13 on 2022-05-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_user_hhs_id'),
        ('users', '0033_user_nextgen_xid'),
    ]

    operations = [
    ]
