# Generated by Django 3.2.13 on 2022-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_user_hhs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nextgen_xid',
            field=models.CharField(default=1, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
