# Generated by Django 3.2.13 on 2022-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_merge_0033_alter_user_hhs_id_0033_user_nextgen_xid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nextgen_xid',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
