# Generated by Django 3.2.15 on 2023-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20230306_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_requested_date',
            field=models.DateTimeField(null=True),
        ),
    ]
