# Generated by Django 3.2.15 on 2023-04-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_access_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_requested_date',
            field=models.DateTimeField(null=True),
        ),
    ]
