# Generated by Django 3.2.15 on 2025-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_users_digit_group_add_datafile_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feature_flags',
            field=models.JSONField(default={}, help_text='Feature flags for this data file.'),
        ),
    ]
