# Generated by Django 3.2.15 on 2025-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_changerequestauditlog_userchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchangerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this feedback was reviewed', null=True),
        ),
    ]
