# Generated by Django 3.2.15 on 2025-07-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_changerequestauditlog_userchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchangerequest',
            name='field_name',
            field=models.CharField(help_text='The name of the field being changed, possible values include: first_name, last_name, regions', max_length=100),
        ),
    ]
