# Generated by Django 3.2.15 on 2025-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_changerequestauditlog_userchangerequest'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='deactivated',
            field=models.BooleanField(default=False, help_text='Is used as flag for deleted accounts.', verbose_name='deactivated'),
        ),
    ]
