# Generated by Django 3.2.15 on 2025-10-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_feedback_addmetafields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deactivated',
        ),
    ]
