# Generated by Django 3.2.15 on 2022-11-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0005_stt_stt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stt',
            name='filenames',
            field=models.JSONField(blank=True, max_length=512, null=True),
        ),
    ]
