# Generated by Django 3.2.15 on 2022-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0005_stt_stt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stt',
            name='ssp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
