# Generated by Cameron
import csv
from pathlib import Path
from ..models import STT
import os

from django.db import migrations, models


def _update(path):
    data_dir = Path(__file__).resolve().parent.parent  /"management" / "commands" / "data"

    with open(data_dir / path) as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            stt = STT.objects.get(code=row["Code"])
            stt.ssp = row["SSP"] == "0"
            stt.save()

def _update_stts(apps, schema_editor):
    _update("states.csv")
    _update("territories.csv")
    _update("tribes.csv")


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0006_alter_stt_filenames'),
    ]

    is_pytest = os.environ.get('PYTEST')

    if is_pytest:
        operations = [
            migrations.RunPython(_update_stts),
        ]
    else:
        operations = [
            migrations.AddField(
                model_name='stt',
                name='ssp',
                field=models.BooleanField(default=False),
            ),
            migrations.RunPython(_update_stts),
        ]
