# Generated by Cameron
import csv
from pathlib import Path
from ..models import STT

from django.db import migrations


def _update(path):
    data_dir = Path(__file__).resolve().parent.parent  /"management" / "commands" / "data"

    with open(data_dir / path) as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            print(row["Code"])
            stt = STT.objects.get(code=row["Code"])
            stt.ssp = row["SSP"] == "0"
            stt.save()

def _update_stts(apps, schema_editor):
    _update("states.csv")
    _update("territories.csv")
    _update("tribes.csv")


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0006_alter_stt_filenames'),
    ]

    operations = [
        migrations.RunPython(_update_stts),
    ]
