# Generated by Django 3.2.15 on 2024-02-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0010_alter_stt_stt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stt',
            name='fa_feld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stts.region'),
        ),
    ]
