# Generated by Django 3.2.15 on 2024-02-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0011_stt_fake_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stt',
            name='fake_field',
        ),
        migrations.AddField(
            model_name='stt',
            name='fa_feld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stts.region'),
        ),
    ]
