version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    branches:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Test: Build and Spin-up Local Django API Service"
          command: "cd tdrs-backend; docker-compose up -d --build "
      - run:
          name: "Tear Down Local Django API Service"
          command: "cd tdrs-backend; docker-compose down "
      - run:
          name:  "Test: Execute Python Unit Tests and Linting Test"
          command: "cd tdrs-backend; docker-compose run web sh -c \"python manage.py test && flake8\""
      - run:
          name: "Test: Zap Vulnerability Scanner "
          command: "cd tdrs-backend; ./zap-scanner.sh"

workflows:
  build-and-test:
    jobs:
      - build
