version: 2.1

executors:
  machine-executor:
    machine:
      docker_layer_caching: false
      image: ubuntu-2004:202104-01

jobs:
  test:
    executor: machine-executor
    parameters:
      project-slug:
        type: string
        default: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
    steps:
      - run: echo << parameters.project-slug >>

workflows:
  pipeline-test:
    jobs:
      - test
