version: 2.1

executors:
  machine-executor:
    machine:
      docker_layer_caching: false
      image: ubuntu-2004:202104-01

jobs:
  test:
    executor: machine-executor
    parameters:
      project-slug:
        default: echo << pipeline.project.git_url >> | sed 's/https:\/\/github.com\///g'
    steps:
      - run: echo << parameters.project-slug >>

workflows:
  pipeline-test:
    jobs:
      - test
