version: 2.1

orbs:
  node: circleci/node@4.7.0
  terraform: circleci/terraform@2.1.0
  jq: circleci/jq@2.2.0

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.10.1
        user: root
  machine-executor:
    machine:
      docker_layer_caching: false
      image: ubuntu-2004:202104-01

jobs:
  test:
    steps:
      - echo << pipeline.project.git_url >>

workflows:
  pipeline-test:
    jobs:
      - test
