version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cypress/base:10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Package Dependencies
          command: "cd tdrs-frontend; yarn"
      - run:
          name: Run ESLint
          command: "cd tdrs-frontend; yarn lint"
      - run:
          name: Run Pa11y Accessibility Tests
          command: "cd tdrs-frontend; yarn test:accessibility"
      - run:
          name: Run Jest Unit Tests
          command: "cd tdrs-frontend; yarn test:ci"
      - run:
          name: Run Cypress Integration Tests
          command: "cd tdrs-frontend; yarn cy:run:ci"
workflows:
  build-and-test:
    jobs:
      - build
