# Generated by Django 3.2.15 on 2023-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsererror',
            name='case_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parsererror',
            name='rpt_month_year',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
