# Generated by Django 3.2.15 on 2023-04-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsererror',
            name='case_number',
            field=models.IntegerField(null=True),
        ),
    ]
