# Generated by Django 3.2.15 on 2023-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_alter_parsererror_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsererror',
            name='column_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
