# Generated by Django 3.2.15 on 2024-10-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0011_parsererror_row_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsererror',
            name='validator_id',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
