# Generated by Django 5.2.14 on 2026-09-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_baselog'),
        ('parsers', '0017_shadowdatafilesummary_shadowparsererror'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseExecutionLog',
            fields=[
                ('baselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baselog')),
                ('reparse_meta_id', models.PositiveIntegerField(blank=True, null=True)),
                ('parser_class', models.CharField(blank=True, max_length=128, null=True)),
                ('execution_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Accepted with Errors', 'Accepted With Errors'), ('Partially Accepted with Errors', 'Partially Accepted'), ('Rejected', 'Rejected')], max_length=32, null=True)),
                ('total_records_processed', models.PositiveIntegerField(default=0)),
                ('total_errors_generated', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['reparse_meta_id'], name='parsers_pel_reparse_idx'), models.Index(fields=['status'], name='parsers_pel_status_idx')],
            },
            bases=('core.baselog',),
        ),
    ]
