# Generated by Django 5.2.14 on 2026-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_baselog'),
        ('parsers', '0018_parseexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseexecutionlog',
            name='upload_source',
            field=models.CharField(blank=True, choices=[('API', 'API'), ('Frontend', 'Frontend')], max_length=16, null=True, verbose_name='Upload Source'),
        ),
        migrations.AddIndex(
            model_name='parseexecutionlog',
            index=models.Index(fields=['upload_source'], name='parsers_pel_source_idx'),
        ),
    ]
