global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'no-reply@tanfdata.acf.hhs.gov'
  smtp_auth_username: 'apikey'
  # I promise the below is fake
  smtp_auth_password: '{{ send_grid_api_key }}'
  smtp_auth_password_file: '/etc/postfix/sasl_passwd'

