# Generated by Django 3.2.15 on 2022-10-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0011_alter_datafile_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='ssp',
            field=models.BooleanField(default=True),
        ),
    ]
