# Generated by Django 3.2.15 on 2024-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0012_datafile_s3_versioning_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='total_number_of_records_in_file',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='total_number_of_records_created',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
