# Generated by Django 3.2.15 on 2024-08-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0030_reparse_meta_model'),
        ('data_files', '0012_datafile_s3_versioning_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='reparse_meta',
            field=models.ForeignKey(blank=True, help_text='Re-parse event this file is associated with.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reparse_meta', to='search_indexes.reparsemeta'),
        ),
    ]
