# Generated by Django 3.2.15 on 2024-10-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0013_datafile_reparse_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='reparse_meta_models',
        ),
    ]
