# Generated by Django 3.2.15 on 2024-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0014_datafile_reparse_meta'),
        ('search_indexes', '0031_reparsefilemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='reparses',
            field=models.ManyToManyField(help_text='Reparse events this file has been associated with.', related_name='files', through='search_indexes.ReparseFileMeta', to='search_indexes.ReparseMeta'),
        ),
    ]
