# Generated by Django 3.2.15 on 2025-01-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0016_remove_datafile_reparse_meta_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'permissions': [('can_view_FRA', 'Can view FRA datafiles'), ('can_change_FRA', 'Can change FRA datafiles'), ('can_delete_FRA', 'Can delete FRA datafiles')]},
        ),
    ]
