# Generated by Django 3.2.15 on 2026-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0024_alter_datafile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafile",
            name="state",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("virus_scanning", "Virus scanning"),
                    ("scan_failed", "Scan failed"),
                    ("validated", "Validated"),
                    ("parsing", "Parsing"),
                    ("parsed_with_errors", "Parsed with errors"),
                    ("parsed_clean", "Parsed clean"),
                    ("ingesting", "Ingesting"),
                    ("ingest_failed", "Ingest failed"),
                    ("stuck", "Stuck"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="uploaded",
                max_length=32,
            ),
            preserve_default=True,
        ),
    ]
