# Generated by Django 5.2.14 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0031_backfill_datafile_section_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafile",
            name="parser_mode",
            field=models.CharField(
                choices=[
                    ("disabled", "Python only"),
                    ("shadow", "Python and Go shadow"),
                    ("production", "Go production"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
