# Generated by Codex on 2026-08-14

import django.db.models.deletion
from django.db import migrations, models


SUBMISSION_STATE_CHOICES = [
    ("uploaded", "Uploaded"),
    ("virus_scan_started", "Virus scan started"),
    ("virus_scan_failed", "Virus scan failed"),
    ("virus_scan_completed", "Virus scan completed"),
    ("reparse_requested", "Reparse requested"),
    ("parse_started", "Parse started"),
    ("parse_failed", "Parse failed"),
    ("parsed_with_errors", "Parsed with errors"),
    ("parse_completed", "Parse completed"),
    ("stuck", "Stuck"),
    ("completed", "Completed"),
    ("canceled", "Canceled"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("data_files", "0031_backfill_datafile_section_ref"),
        ("users", "0001_initial"),
    ]

    operations = [
        # No historical rows are backfilled. Existing DataFile rows begin
        # recording transition history the next time their state changes.
        migrations.CreateModel(
            name="DataFileStateTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        choices=SUBMISSION_STATE_CHOICES,
                        max_length=32,
                    ),
                ),
                (
                    "next_state",
                    models.CharField(
                        choices=SUBMISSION_STATE_CHOICES,
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, max_length=64, null=True)),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reparse_meta_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_file_state_transitions",
                        to="users.user",
                    ),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="state_transitions",
                        to="data_files.datafile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="datafilestatetransition",
            index=models.Index(
                fields=["data_file", "-created_at"],
                name="dfstate_datafile_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datafilestatetransition",
            index=models.Index(fields=["source"], name="data_files_source_3a5de1_idx"),
        ),
        migrations.AddIndex(
            model_name="datafilestatetransition",
            index=models.Index(
                fields=["task_name"],
                name="data_files_task_na_94f15f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datafilestatetransition",
            index=models.Index(
                fields=["reparse_meta_id"],
                name="data_files_reparse_4ba50f_idx",
            ),
        ),
    ]
