# Generated by Django 5.2.14 on 2026-09-15 18:20

import tdpservice.backends
import tdpservice.common.fields
import tdpservice.data_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0032_datafilestatetransition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadowdatafile',
            name='file',
            field=tdpservice.common.fields.S3VersionedFileField(blank=True, null=True, storage=tdpservice.backends.DataFilesS3Storage, upload_to=tdpservice.data_files.models.get_shadow_s3_upload_path, version_id_field='s3_versioning_id'),
        ),
        migrations.AlterField(
            model_name='shadowdatafile',
            name='program_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shadowdatafile',
            name='section',
            field=models.CharField(max_length=32),
        ),
    ]
