# Generated by Django 5.2.14 on 2026-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0035_datafile_upload_source_shadowdatafile_upload_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='upload_source',
            field=models.CharField(choices=[('API', 'API'), ('Frontend', 'Frontend')], default='Frontend', max_length=16, verbose_name='Upload Source'),
        ),
        migrations.AlterField(
            model_name='shadowdatafile',
            name='upload_source',
            field=models.CharField(choices=[('API', 'API'), ('Frontend', 'Frontend')], default='Frontend', max_length=16, verbose_name='Upload Source'),
        ),
    ]
