{
 "title": "Uptime/Health",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "app_env",
    "label": "Backend environment",
    "query": "prod, staging, develop, qasp, raft, local"
   },
   {
    "name": "pg_env",
    "label": "Database environment",
    "query": "production, staging, dev, local"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 }, "options": { "content": "# Backend - django" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 }, "options": { "content": "# Database - postgres" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 }, "options": { "content": "# Worker - celery" } },
  {
   "title": "Backend - Active Alerts",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database - Active Alerts",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alive Workers (Celery)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(celery_workers{job=~\"celery-$app_env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Received (Celery)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(celery_tasks_total{state=\"RECEIVED\", job=~\"celery-$app_env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (Backend)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=~\"tdp-backend-$app_env\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Fired (Backend)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=\"tdp-backend-$app_env\",alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (Database)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=~\"postgres-$pg_env\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Fired (Database)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=~\"postgres-$pg_env\", alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Succeeded (Celery)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(celery_tasks_total{state=\"SUCCESS\", job=~\"celery-$app_env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Failed (Celery)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(celery_tasks_total{state=\"FAILURE\", job=~\"celery-$app_env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (Backend)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{job=~\"tdp-backend-$app_env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate (Backend)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=~\"tdp-backend-$app_env\",status!~\"2.+|3.+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage (Database)",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=~\"postgres-$pg_env\"}[$__rate_interval]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "DB Queries/Errors (Backend)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(django_db_execute_total{job=~\"tdp-backend-$app_env\"}[$__rate_interval]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(irate(django_db_errors_total{job=~\"tdp-backend-$app_env\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Average Memory Usage (Database)",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=~\"postgres-$pg_env\"}[$__rate_interval]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{job=~\"postgres-$pg_env\"}[$__rate_interval]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "System Resource Utilization (Backend)",
   "type": "timeseries",
   "description": "The average percentage utilization of backend system resources over a 5 min interval",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=~\"node-$app_env\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU %"
    },
    {
     "expr": "avg_over_time(\n  (\n    (node_memory_MemTotal_bytes{job=~\"node-$app_env\"} - node_memory_MemAvailable_bytes{job=~\"node-$app_env\"})\n    / node_memory_MemTotal_bytes{job=~\"node-$app_env\"} * 100\n  )[$__rate_interval:]\n)",
     "legendFormat": "Memory %"
    },
    {
     "expr": "avg_over_time(\n  (\n    100 * (node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\",job=~\"node-$app_env\"} \n    - node_filesystem_free_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\",job=~\"node-$app_env\"})\n    / node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\",job=~\"node-$app_env\"}\n  )[$__rate_interval:]\n)",
     "legendFormat": "Disk %"
    }
   ]
  },
  {
   "title": "Average Memory Usage (Backend)",
   "type": "timeseries",
   "description": "Memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time((node_memory_MemTotal_bytes{job=~\"node-$app_env\"} - node_memory_MemAvailable_bytes{job=~\"node-$app_env\"})[$__rate_interval:])",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}