version: "3"
services:
  zaproxy:
    image: owasp/zap2docker-weekly
    command: sleep 3600
    volumes:
      - ./reports:/zap/wrk/:rw
  tdp-frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    volumes:
      - ./:/home/node/app
    networks:
      - local
networks:
  local:
    driver: bridge
