version: "3.4"
services:
  zaproxy:
    image: owasp/zap2docker-stable:2.11.0
    container_name: zap-scan
    command: sleep 3600
    ports:
      - 8090:8090
    networks:
      - local
    volumes:
      - ./reports:/zap/wrk/:rw
      - ../scripts/zap-hook.py:/zap/scripts/zap-hook.py:ro
  tdp-frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      target: nginx
    ports:
      - 3000:80
      - 8080:8080

    volumes:
      - ./:/home/node/app
    environment:
      - NGINX_FRONTEND=tdp-frontend
      - BACK_END=web
      - LOCAL_DEV=true
    command: >
      /bin/sh -c
      "envsubst '
      $${BACK_END} $${NGINX_FRONTEND} $${LOCAL_DEV}
      '< /etc/nginx/default.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

networks:
  local:
    driver: bridge

  default:
    external:
      name: external-net