# Base image for frontend builds
# Note: Chromium/Puppeteer is NOT needed here - pa11y tests run on CI machine directly
FROM node:22-alpine AS localdev

USER node

RUN mkdir /home/node/app/ && chown -R node:node /home/node/app
WORKDIR /home/node/app

# Copy package.json and run yarn install before copying the rest of the app in
# to allow Docker to cache the yarn layer to prevent unnecessary installations
# when code changes occur
COPY --chown=node:node package.json yarn.lock ./

# Install all dependencies (devDependencies needed because @redux-devtools/extension is imported in src/configureStore.js)
# TODO: Move @redux-devtools/extension to dependencies in package.json, then use --omit=dev to save ~500MB
RUN yarn install --frozen-lockfile --production --non-interactive && \
    yarn cache clean

ENV PORT=80
EXPOSE 80
