services:
  tdp-frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        REGISTRY_OWNER: ${REGISTRY_OWNER:-hhs}
      target: nginx
    ports:
      - 3000:80
      - 8080:8080
    networks:
      - default
    volumes:
      - ./:/home/node/app
      - ~/tdp-logs/nginx:/var/log/nginx
    environment:
      - NGINX_FRONTEND=tdp-frontend
      - BACK_END=web
      - LOCAL_DEV=true
      - GRAFANA=grafana
      - ALERTS=alertmanager
      - FARO_RECEIVER=alloy
      - REACT_APP_DEVAUTH=${REACT_APP_DEVAUTH}
    command: >
      /bin/sh -c
      "echo 'starting nginx' &&
        envsubst '$${BACK_END} $${GRAFANA} $${ALERTS} $${FARO_RECEIVER}' < /etc/nginx/locations.conf > /etc/nginx/locations_.conf &&
        rm /etc/nginx/locations.conf &&
        cp /etc/nginx/locations_.conf /etc/nginx/locations.conf &&
       envsubst '
      $${BACK_END} $${NGINX_FRONTEND} $${LOCAL_DEV}
      '< /etc/nginx/default.conf.template
      > /etc/nginx/nginx.conf &&
      nginx -g 'daemon off;'"
    depends_on:
     - web
