"""Meta data file for validators to map their IDs and what the priorities are for STT reports."""

validator_id_map = {
    1: ('category1', 'recordIsNotEmpty'),
    2: ('category1', 'recordHasLength'),
    3: ('category1', 'recordHasLengthBetween'),
    4: ('category1', 'recordStartsWith'),
    5: ('category1', 'caseNumberNotEmpty'),
    6: ('category1', 'validate_fieldYearMonth_with_headerYearQuarter'),
    7: ('category1', 'validateRptMonthYear'),
    8: ('category1', 't3_m3_child_validator'),
    9: ('category1', 'calendarQuarterIsValid'),
    10: ('category1', 'validate_tribe_fips_program_agree'),
    11: ('category1', 'validate_header_section_matches_submission'),
    12: ('category1', 'validate_header_rpt_month_year'),
    13: ('category2', 'isEqual'),
    14: ('category2', 'isNotEqual'),
    15: ('category2', 'isOneOf'),
    16: ('category2', 'isNotOneOf'),
    17: ('category2', 'isGreaterThan'),
    18: ('category2', 'isLessThan'),
    19: ('category2', 'isBetween'),
    20: ('category2', 'startsWith'),
    21: ('category2', 'contains'),
    22: ('category2', 'isNumber'),
    23: ('category2', 'isAlphaNumeric'),
    24: ('category2', 'isEmpty'),
    25: ('category2', 'isNotEmpty'),
    26: ('category2', 'isBlank'),
    27: ('category2', 'hasLength'),
    28: ('category2', 'hasLengthGreaterThan'),
    29: ('category2', 'intHasLength'),
    30: ('category2', 'isNotZero'),
    31: ('category2', 'dateYearIsLargerThan'),
    32: ('category2', 'dateMonthIsValid'),
    33: ('category2', 'dateDayIsValid'),
    34: ('category2', 'quarterIsValid'),
    35: ('category2', 'validateRace'),
    36: ('category2', 'validateHeaderUpdateIndicator'),
    37: ('category3', 'isEqual'),
    38: ('category3', 'isNotEqual'),
    39: ('category3', 'isOneOf'),
    40: ('category3', 'isNotOneOf'),
    41: ('category3', 'isGreaterThan'),
    42: ('category3', 'isLessThan'),
    43: ('category3', 'isBetween'),
    44: ('category3', 'startsWith'),
    45: ('category3', 'contains'),
    46: ('category3', 'isNumber'),
    47: ('category3', 'isAlphaNumeric'),
    48: ('category3', 'isEmpty'),
    49: ('category3', 'isNotEmpty'),
    50: ('category3', 'isBlank'),
    51: ('category3', 'hasLength'),
    52: ('category3', 'hasLengthGreaterThan'),
    53: ('category3', 'intHasLength'),
    54: ('category3', 'isNotZero'),
    55: ('category3', 'isOlderThan'),
    56: ('category3', 'validateSSN'),
    57: ('category3', 'sumIsEqual'),
    58: ('category3', 'sumIsLarger'),
    59: ('category3', 'validate__FAM_AFF__SSN'),
    60: ('category3', 'validate__WORK_ELIGIBLE_INDICATOR__HOH__AGE'),
    61: ('category4', '__validate_family_affiliation'),
    62: ('category4', '__validate_s1_records_are_related'),
    63: ('category4', '__validate_case_closure_employment'),
    64: ('category4', '__validate_case_closure_ftl'),
    65: ('category4', '__validate_s2_records_are_related'),
    66: ('category4', '__validate_t5_atd_and_ssi'),
}

priority_validators = {
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60
}
