server:
  http_listen_port: 8080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.apps.internal:8080/loki/api/v1/push

scrape_configs:
  - job_name: syslog-rfc5424
    syslog:
      listen_address: 0.0.0.0:5514
      idle_timeout: 60s
      labels:
        job: syslog-rfc5424
