# Generated by Django 5.2.14 on 2026-06-29 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("etl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etlartifact",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL Artifact",
                "verbose_name_plural": "ETL Artifacts",
            },
        ),
        migrations.AlterModelOptions(
            name="etlnoderun",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL Node Run",
                "verbose_name_plural": "ETL Node Runs",
            },
        ),
        migrations.AlterModelOptions(
            name="etlpipelinerun",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ETL Pipeline",
                "verbose_name_plural": "ETL Pipelines",
            },
        ),
        migrations.AlterModelOptions(
            name="etlqaresult",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL QA Result",
                "verbose_name_plural": "ETL QA Results",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweight",
            options={
                "verbose_name": "Statistical Weight",
                "verbose_name_plural": "Statistical Weights",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweightcandidate",
            options={
                "ordering": [
                    "pipeline_run_id",
                    "stt_code",
                    "reporting_month",
                    "stratum",
                ],
                "verbose_name": "Statistical Weight Candidate",
                "verbose_name_plural": "Statistical Weight Candidates",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweightsactivefamilycount",
            options={
                "ordering": [
                    "pipeline_run_id",
                    "stt_code",
                    "reporting_month",
                    "stratum",
                ],
                "verbose_name": "Statistical Weights Active Family Count",
                "verbose_name_plural": "Statistical Weights Active Family Counts",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweightsaggregatecasecount",
            options={
                "ordering": ["pipeline_run_id", "stt_code", "reporting_month"],
                "verbose_name": "Statistical Weights Aggregate Case Count",
                "verbose_name_plural": "Statistical Weights Aggregate Case Counts",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweightsstratumcasecount",
            options={
                "ordering": [
                    "pipeline_run_id",
                    "stt_code",
                    "reporting_month",
                    "stratum",
                ],
                "verbose_name": "Statistical Weights Stratum Case Count",
                "verbose_name_plural": "Statistical Weights Stratum Case Counts",
            },
        ),
    ]
