# Generated by Django 5.2.14 on 2026-06-29 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("etl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etlintermediateoutput",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL Intermediate Output",
                "verbose_name_plural": "ETL Intermediate Outputs",
            },
        ),
        migrations.AlterModelOptions(
            name="etlnoderun",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL Node Run",
                "verbose_name_plural": "ETL Node Runs",
            },
        ),
        migrations.AlterModelOptions(
            name="etloutput",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL Output",
                "verbose_name_plural": "ETL Outputs",
            },
        ),
        migrations.AlterModelOptions(
            name="etlpipelinerun",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ETL Pipeline",
                "verbose_name_plural": "ETL Pipelines",
            },
        ),
        migrations.AlterModelOptions(
            name="etlqaresult",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL QA Result",
                "verbose_name_plural": "ETL QA Results",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweight",
            options={
                "verbose_name": "Statistical Weight",
                "verbose_name_plural": "Statistical Weights",
            },
        ),
    ]
