#workflows:
  enable-versioning-dev:
    jobs:
      - enable-versioning

  enable-versioning-staging:
    jobs:
      - enable-versioning:
        filters:
            branches:
              unless:
                or:
                  - devops/1007-develop-fake
                  - main
                  - master
      - enable-versioning:
          target_env: staging
          cf-password: CF_PASSWORD_STAGING
          cf-username: CF_USERNAME_STAGING
          cf-space: tanf-staging
          filters:
            branches:
              only:
                - main
      - enable-versioning:
          target_env: prod
          cf-password: CF_PASSWORD_PROD
          cf-username: CF_USERNAME_PROD
          cf-space: tanf-prod
          filters:
            branches:
              only:
                - master
      - enable-versioning:
          target_env: develop
          cf-password: CF_PASSWORD_STAGING
          cf-username: CF_USERNAME_STAGING
          cf-space: tanf-staging
          filters:
            branches:
              only:
                - devops/1007-develop-fake

  # enable-versioning-develop:
  #   unless: << pipeline.parameters.run_dev_deployment >>
  #   jobs:
  #     - enable-versioning:
  #         target_env: develop
  #         cf-password: CF_PASSWORD_STAGING
  #         cf-username: CF_USERNAME_STAGING
  #         cf-space: tanf-staging
  #         filters:
  #           branches:
  #             only:
  #               - devops/1007-develop-fake

  # enable-versioning-production:
  #   unless: << pipeline.parameters.run_dev_deployment >>
  #   jobs:
  #     - enable-versioning:
  #         target_env: prod
  #         cf-password: CF_PASSWORD_PROD
  #         cf-username: CF_USERNAME_PROD
  #         cf-space: tanf-prod
  #         filters:
  #           branches:
  #             only:
  #               - master
