# workflows:
  owasp-scan:
    when: << pipeline.parameters.run_owasp_scan >>
    jobs:
      - backend-owasp-scan
      - frontend-owasp-scan
  
  nightly:
    when: << pipeline.parameters.build_and_test_all >>
    jobs:
      - nightly-owasp-scan:
          target_env: develop
