# workflows:
  owasp-scan:
    when: << pipeline.parameters.run_owasp_scan >>
    jobs:
      - backend-owasp-scan
      - frontend-owasp-scan
  
  nightly:
    jobs:
      - nightly-owasp-scan:
          target_env: develop
          filters:
            branches:
              only:
                - develop
      - nightly-owasp-scan:
          target_env: staging
          filters:
            branches:
              only:
                - main
      - nightly-owasp-scan:
          target_env: prod
          cf_password: CF_PASSWORD_PROD
          cf_username: CF_USERNAME_PROD
          cf_space: tanf-prod
          filters:
            branches:
              only:
                - master
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
                - main
                - master
