name: Build and test All for PRs
on:
  pull_request:
    branches-ignore: #handled in circleci
      - main
      - master
      - 'devops/branch-ref-fix'
    types: [review_requested, ready_for_review, synchronize]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.txt'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
jobs:
  build_and_test_pr:
    runs-on: ubuntu-latest
    name: Initiate deploy job in CircleCI
    steps:
      - uses: actions/checkout@v2
      - name: Circle CI Deployment Trigger
        id: curl-circle-ci
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_CI_V2_TOKEN }}
          project-slug: ${{ github.repository }}
          branch: ${{ (github.event_name == 'pull_request') && github.head_ref || github.ref_name }}
          payload: '{
            "build_and_test_all": true,
            "triggered": true
          }'